#!/bin/sh

setxkbmap -layout us,es -variant altgr-intl, -option grp:menu_toggle -option grp_led:scroll -option ctrl:nocaps

# NetworkManage applet
exec --no-startup-id nm-applet

# Multimedia keys settings
exec gnome-settings-daemon

#Autostart
exec --no-startup-id nitrogen --restore
